apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: alfonsobalmori/myapp:eb780ce
        ports:
        - containerPort: 3000
        env:
        - name: MYSQLDB_HOST
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: MYSQLDB_HOST
        - name: MYSQLDB_USER
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: MYSQLDB_USER
        - name: MYSQLDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: MYSQLDB_PASSWORD
        - name: MYSQLDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: MYSQLDB_DATABASE
        imagePullSecrets:
        - name: dockerhub-secret

